site_name: Портолио работ за 3 - 4 семестр 
site_description: Отчёт в виде представление сайт со всеми проделлаными работами за 3-4 семестр по дисциплине "Программирование"
site_author: Елена Байкова

repo_url: https://github.com/YOUR_USERNAME/portfolio-site
repo_name: GitHub


nav:
  - Главная: index.md
  - Лабораторные: labs.md
  - Проекты: projects.md
  - Доклады: reports.md



theme:
  name: material
  language: ru

  palette:
    - scheme: default
      primary: pink
      accent: pink

  font:
    text: Poppins
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: "2-2"

extra_css:
  - stylesheets/extra.css


  